name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-publish:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v4

    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false # On ne pousse pas encore l'image, seulement pour le scan
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    
    - name: Install Trivy
      run: |
        wget https://github.com/aquasecurity/trivy/releases/download/v0.29.1/trivy_0.29.1_Linux-64bit.deb
        sudo dpkg -i trivy_0.29.1_Linux-64bit.deb

    
    - name: Scan Docker image for vulnerabilities with Trivy
      run: |
        trivy image --no-progress --exit-code 1 ghcr.io/${{ github.repository }}:${{ steps.meta.outputs.tags }}
      
    
    - name: Push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
