name: Build, Scan and Publish Docker Image

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-publish:
    name: Build, Scan and Publish Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
    # Vérifie le code du dépôt
    - name: Checkout repository
      uses: actions/checkout@v4

    # Configure Docker Buildx pour permettre les builds multi-plateformes
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Connexion au registre GHCR
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Extraction des métadonnées de l'image Docker
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    # Build de l'image Docker sans la pousser (scan uniquement)
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false  # Ne pas pousser l'image, juste la créer pour le scan
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    # Installer Trivy pour le scan de vulnérabilités
    - name: Install Trivy
      run: |
        wget https://github.com/aquasecurity/trivy/releases/download/v0.29.1/trivy_0.29.1_Linux-64bit.deb
        sudo dpkg -i trivy_0.29.1_Linux-64bit.deb

    # Scanner l'image Docker pour des vulnérabilités avec Trivy
    - name: Scan Docker image for vulnerabilities with Trivy
      run: |
        trivy image --no-progress --exit-code 1 ghcr.io/${{ github.repository }}:${{ steps.meta.outputs.tags }}

    # Si le scan est réussi, publier l'image Docker
    - name: Push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true  # Push l'image si le scan est réussi
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
